project:
  type: website

website:
  title: "Dr Kyriakos Deliparaschos"
  navbar:
    left:
      - text: About
        href: about.qmd
      - research_interests.qmd
      - publications.qmd
      - text: Teaching
        menu:
        - current_courses.qmd
        - past_courses.qmd
      - professional_service.qmd
      - contact_info.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true




