---
title: "Past Courses"
format: html
---

<h4>Cyprus University of Technology</h4>
<ul>
    <li><strong>EE311</strong> - Control Systems</li>
    <li><strong>EE317</strong> - Communication Systems</li>
</ul>
<h4>National Technical University of Athens</h4>
<ul>
    <li>Control and Robotics Systems Lab exercises:<ul class="circle">
            <li>Three-term (PID) control with analogue circuits</li>
            <li>Servomechanism (ES230) system analysis</li>
            <li>Embedded control system (MIDICOM)</li>
            <li>Design of control systems in MATLAB</li>
            <li>Automatic control of robotic joint</li>
            <li>Classic robot (Adept) control (disturbance compensation)</li>
            <li>Robot (Adept) Programming</li>
            <li>Mobile robot (RoboSoft) control</li>
            <li>Robotic (palletizing) cell (FMS)</li>
            <li>Pendubot control</li>
            <li>Fuzzy inference and control in MATLAB</li>
    </li></ul>
</ul>

<h4>Greenwich University (NYC Athens Campus)</h4>
<ul>
    <li><strong>COMP1171</strong> - Computer & Communication Systems I</li>
    <li><strong>COMP1588</strong> - Computer Systems Architectures</li>
    <li><strong>COMP1564</strong> - Systems Programming Technologies</li>
    <li><strong>COMP1391</strong> - Systems Development</li>
    <li>Networking Technology (HND)</li>
    <li>Database concepts (HND)</li>
</ul>

<h4>Hertfordshire University (IST Athens Campus)</h4>
<ul>
    <li><strong>6COM1012</strong> (3FEN0161) - Computer Network Protocols and Architecture</li>
    <li><strong>7COM0099</strong> (MFEN0100) - Software Development Tools and Methods</li>
</ul>